### ISSUE TITLE
Chance of branch conflict within large organisation

### ISSUE THREAD

**Issue by nickw444** [qw3rtman/git-fire#3] opened 2015-10-04 09:10 UTC
In the case of a fire in a large organisation, I feel that using only the unix epoch and branch name could be catastrophic, since many developers will perform `git-fire` at the exact same moment as each other.

I suggest this is fixed by using some sort of UUID to prevent any kind of conflict that multiple developers may have in the case of a fire.

**Comment by FrankyBoy** [comment] 2015-10-04 11:50
Duplicate of #2

**Closed as completed** 2015-10-04 12:41 UTC
